### ISSUE TITLE
AWS credentials provider configuration for s3tables catalog

### ISSUE THREAD

**Issue by harryharanb** [awslabs/s3-tables-catalog#20]
We are running our workload in spark on eks and would like to use `WebIdentityTokenCredentialsProvider` for s3tablescatalog.  

spark conf `spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.WebIdentityTokenCredentialsProvider` is used to set IRSA/IAM based authentication to access s3/glue from our workload. 

How do we setup the same for s3tables. By default `NodeInstanceRole` is being used.

## Error

```
java.lang.RuntimeException: software.amazon.s3tables.shaded.awssdk.services.s3tables.model.AccessDeniedException: User: arn:aws:sts::acctid:assumed-role/eksctl-ekscluster-NodeInstanceRole-r5wn6T6 │
│ DFOpd/i-0a6fd62c909b22527 is not authorized to perform: s3tables:ListNamespaces on resource: arn:aws:s3tables:us-east-1:acctid:bucket/s3tablesbucket (Service: S3Tables, Status Code: 403, Request ID: ) 
```

https://github.com/awslabs/s3-tables-catalog/blob/786ed12ebfb2f9f2f80d42807fc3c53a22aea447/src/software/amazon/s3tables/iceberg/imports/AwsClientProperties.java#L46-L52

**Comment by harryharanb** [comment]
I was able to set the provider as below 

```properties
spark.sql.catalog.s3tablescatalog=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.s3tablescatalog.catalog-impl=software.amazon.s3tables.iceberg.S3TablesCatalog
spark.sql.catalog.s3tablescatalog.client.credentials-provider=software.amazon.s3tables.shaded.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider

## notworking
# spark.sql.catalog.s3tablescatalog.client.credentials-provider=software.amazon.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider
## Cannot initialize software.amazon.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider, it does not implement software.amazon.s3tables.shaded.awssdk.auth.credentials.AwsCredentialsProvider.
```
now WebIdentityTokenFileCredentialsProvider is being used, but getting below error. 

```
24/12/04 22:26:06 ERROR S3TablesCatalog: Failed to list namespaces
software.amazon.s3tables.shaded.awssdk.core.exception.SdkClientException: Unable to load an HTTP implementation from any provider in the chain. You must declare a dependency on an appropriate HTTP implementation or pass in an SdkHttpClient explicitly to the client builder.
        at software.amazon.s3tables.shaded.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
        at software.amazon.s3tables.shaded.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.lambda$buildWithDefaults$1(DefaultSdkHttpClientBuilder.java:49)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at software.amazon.s3tables.shaded.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.buildWithDefaults(DefaultSdkHttpClientBuilder.java:43)
        at software.amazon.s3tables.shaded.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveSyncHttpClient$17(SdkDefaultClientBuilder.java:452)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at software.amazon.s3tables.shaded.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveSyncHttpClient(SdkDefaultClientBuilder.java:452)
        at software.amazon.s3tables.shaded.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$finalizeSyncConfiguration$5(SdkDefaultClientBuilder.java:311)
        at software.amazon.s3tables.shaded.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:604)
        at software.amazon.s3tables.shaded.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:593)
        at software.amazon.s3tables.shaded.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:400)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at software.amazon.s3tables.shaded.awssdk.utils.AttributeMap$Builder.build(AttributeMap.java:362)
        at software.amazon.s3tables.shaded.awssdk.core.client.config.SdkClientConfiguration$Builder.build(SdkClientConfiguration.java:224)
        at software.amazon.s3tables.shaded.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeSyncConfiguration(SdkDefaultClientBuilder.java:313)
        at software.amazon.s3tables.shaded.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:203)
        at software.amazon.s3tables.shaded.awssdk.services.sts.DefaultStsClientBuilder.buildClient(DefaultStsClientBuilder.java:36)
        at software.amazon.s3tables.shaded.awssdk.services.sts.DefaultStsClientBuilder.buildClient(DefaultStsClientBuilder.java:25)
        at software.amazon.s3tables.shaded.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:169)
        at software.amazon.s3tables.shaded.awssdk.services.sts.internal.StsWebIdentityCredentialsProviderFactory$StsWebIdentityCredentialsProvider.<init>(StsWebIdentityCredentialsProviderFactory.java:74)
        at software.amazon.s3tables.shaded.awssdk.services.sts.internal.StsWebIdentityCredentialsProviderFactory$StsWebIdentityCredentialsProvider.<init>(StsWebIdentityCredentialsProviderFactory.java:56)
        at software.amazon.s3tables.shaded.awssdk.services.sts.internal.StsWebIdentityCredentialsProviderFactory.create(StsWebIdentityCredentialsProviderFactory.java:48)
        at software.amazon.s3tables.shaded.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider.<init>(WebIdentityTokenFileCredentialsProvider.java:113)
        at software.amazon.s3tables.shaded.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider.<init>(WebIdentityTokenFileCredentialsProvider.java:50)
        at software.amazon.s3tables.shaded.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider$BuilderImpl.build(WebIdentityTokenFileCredentialsProvider.java:313)
        at software.amazon.s3tables.shaded.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider.create(WebIdentityTokenFileCredentialsProvider.java:133)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.apache.iceberg.common.DynMethods$UnboundMethod.invokeChecked(DynMethods.java:62)
        at org.apache.iceberg.common.DynMethods$UnboundMethod.invoke(DynMethods.java:74)
        at org.apache.iceberg.common.DynMethods$StaticMethod.invoke(DynMethods.java:187)
        at software.amazon.s3tables.iceberg.imports.AwsClientProperties.createCredentialsProvider(AwsClientProperties.java:197)
        at software.amazon.s3tables.iceberg.imports.AwsClientProperties.credentialsProvider(AwsClientProperties.java:176)
        at software.amazon.s3tables.iceberg.imports.AwsClientProperties.applyClientCredentialConfigurations(AwsClientProperties.java:120)
        at software.amazon.s3tables.shaded.awssdk.utils.builder.SdkBuilder.applyMutation(SdkBuilder.java:61)
        at software.amazon.s3tables.iceberg.S3TablesAwsClientFactories$DefaultS3TablesAwsClientFactory.s3tables(S3TablesAwsClientFactories.java:65)
        at software.amazon.s3tables.iceberg.S3TablesCatalog.initialize(S3TablesCatalog.java:234)
        at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:256)
        at org.apache.iceberg.CatalogUtil.buildIcebergCatalog(CatalogUtil.java:310)
        at org.apache.iceberg.spark.SparkCatalog.buildIcebergCatalog(SparkCatalog.java:154)
        at org.apache.iceberg.spark.SparkCatalog.initialize(SparkCatalog.java:753)
        at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:65)
        at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$catalog$1(CatalogManager.scala:54)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
        at org.apache.spark.sql.connector.catalog.CatalogManager.catalog(CatalogManager.scala:54)
        at org.apache.spark.sql.connector.catalog.LookupCatalog$CatalogAndNamespace$.unapply(LookupCatalog.scala:86)
        at org.apache.spark.sql.catalyst.analysis.ResolveCatalogs$$anonfun$apply$1.applyOrElse(ResolveCatalogs.scala:51)
        at org.apache.spark.sql.catalyst.analysis.ResolveCatalogs$$anonfun$apply$1.applyOrElse(ResolveCatalogs.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$2(AnalysisHelper.scala:170)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$1(AnalysisHelper.scala:170)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:323)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning(AnalysisHelper.scala:168)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning$(AnalysisHelper.scala:164)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDownWithPruning(LogicalPlan.scala:32)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$4(AnalysisHelper.scala:175)
        at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1216)
        at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1215)
        at org.apache.spark.sql.catalyst.plans.logical.ShowNamespaces.mapChildren(v2Commands.scala:616)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$1(AnalysisHelper.scala:175)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:323)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning(AnalysisHelper.scala:168)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning$(AnalysisHelper.scala:164)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDownWithPruning(LogicalPlan.scala:32)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning(AnalysisHelper.scala:99)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning$(AnalysisHelper.scala:96)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsWithPruning(LogicalPlan.scala:32)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperators(AnalysisHelper.scala:76)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperators$(AnalysisHelper.scala:75)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:32)
        at org.apache.spark.sql.catalyst.analysis.ResolveCatalogs.apply(ResolveCatalogs.scala:30)
        at org.apache.spark.sql.catalyst.analysis.ResolveCatalogs.apply(ResolveCatalogs.scala:27)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:222)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
        at scala.collection.immutable.List.foldLeft(List.scala:91)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:219)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:211)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:211)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:240)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:236)
        at org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:187)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:236)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:202)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:182)
        at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)
        at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:182)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:223)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:330)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:222)
        at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:77)
        at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:138)
        at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:219)
        at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
        at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:219)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
        at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:218)
        at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:77)
        at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:74)
        at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:66)
        at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
        at org.apache.spark.sql.SparkSession.$anonfun$sql$4(SparkSession.scala:691)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:682)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:713)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:744)
        at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:651)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLDriver.run(SparkSQLDriver.scala:68)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processCmd(SparkSQLCLIDriver.scala:501)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1(SparkSQLCLIDriver.scala:619)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1$adapted(SparkSQLCLIDriver.scala:613)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processLine(SparkSQLCLIDriver.scala:613)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:310)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by vara-bonthu** [comment]
I've reviewed the issue and can confirm there's a AWS credential handling behavior that needs attention with EKS for IRSA using `WebIdentityTokenCredentialsProvider`. 

The system initially attempts to use the node instance role for permissions, but subsequently defaults to the `WebIdentityTokenCredentialsProvider`. I noticed that it's leveraging both Node Instance role and Pod IAM role(IRSA).

See code examples here 

Node IAM role permissions example [here](https://github.com/awslabs/data-on-eks/blob/5769ed431d4577ea30c45cc081f330756da27a6a/analytics/terraform/spark-k8s-operator/addons.tf#L649C1-L687C5)

Pod IAM role [here](https://github.com/awslabs/data-on-eks/blob/5769ed431d4577ea30c45cc081f330756da27a6a/analytics/terraform/spark-k8s-operator/main.tf#L98C1-L156C2)

Spark example [here](https://github.com/awslabs/data-on-eks/blob/5769ed431d4577ea30c45cc081f330756da27a6a/analytics/terraform/spark-k8s-operator/examples/s3-tables/s3table-iceberg-pyspark.py#L33C1-L44C29)

Spark Operator example with config [here](https://github.com/awslabs/data-on-eks/blob/5769ed431d4577ea30c45cc081f330756da27a6a/analytics/terraform/spark-k8s-operator/examples/s3-tables/s3table-spark-operator.yaml#L41C1-L52C33)

**Comment by nabuskey** [comment]
It seems to be related to the way AWS SDK jars are relocated at build time. I was able to use IRSA / WebIdentityToken by building the shadow jar with this line removed: https://github.com/awslabs/s3-tables-catalog/blob/e572e4cae77118361d92bea97b7a20c733ea3407/runtime/build.gradle#L43

Looks like it's similar to this issue: https://github.com/aws/aws-msk-iam-auth/issues/31

**Comment by harryharanb** [comment]
Thanks much @nabuskey . I'm able to access s3 tables from spark on k8s using the jar built locally with the fix you suggested. 

Is this the permenant fix for this issue? Will you be submitting a PR for this?

**Comment by vprus** [comment]
FYI, I got IRSA auth to work with the current version by adding the following at the start of my job:
```
 System.setProperty("software.amazon.s3tables.shaded.awssdk.http.service.impl", "software.amazon.s3tables.shaded.awssdk.http.urlconnection.UrlConnectionSdkHttpService")
```

It does not seem like an excellent long-term solution, but will probably help for now.
