### ISSUE TITLE
register_table procedure not working for s3TablesCatalog as target

### ISSUE THREAD

**Issue by Karthilearns** [awslabs/s3-tables-catalog#24]
Catalog migration to S3TablesCatalog via register_table procedure fails. Also I'm attaching the sample code used to achieve this. Please help us in this regard. 

```
public class NessieToS3CatalogMigrator {
    public static void main(String[] args) {
        SparkSession session = SparkSession.builder()
                .master("local[*]")
                .config("spark.jars.packages","software.amazon.s3:s3-tables-catalog-for-iceberg:0.1.0")
                .config("spark.sql.extensions","org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
                .config("spark.sql.catalog.s3tablesbucket","org.apache.iceberg.spark.SparkCatalog")
                .config("spark.sql.catalog.s3tablesbucket.catalog-impl","software.amazon.s3tables.iceberg.S3TablesCatalog")
                .config("spark.sql.catalog.s3tablesbucket.warehouse","<TableBucketARN>")
                .config("spark.sql.catalog.s3tablesbucket.client.region","<TableBucketRegion>")
                .config("spark.sql.catalog.nessie.uri","http://localhost:19120/api/v1")
                .config("spark.sql.catalog.nessie.ref","main")
                .config("spark.sql.catalog.nessie.authentication.type","NONE")
                .config("spark.sql.catalog.nessie.catalog-impl","org.apache.iceberg.nessie.NessieCatalog")
                .config("spark.sql.catalog.nessie.warehouse","s3a://bucketName/folderpath/")
                .config("spark.sql.catalog.nessie","org.apache.iceberg.spark.SparkCatalog")
                .config("fs.s3.impl","org.apache.hadoop.fs.s3a.S3AFileSystem")
                .getOrCreate();

        session.sql("  CALL s3tablesbucket.system.register_table(\n" +
                "    's3tablesbucket.stores.employee', 's3a://xxxx/v3.metadata.json'" +
                "    )");

    }
}
```

Error : 

```
Exception in thread "main" java.lang.RuntimeException: Persisting failure
 at software.amazon.s3tables.iceberg.S3TablesCatalogOperations.doCommit(S3TablesCatalogOperations.java:247)
 at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:128)
 at org.apache.iceberg.BaseMetastoreCatalog.registerTable(BaseMetastoreCatalog.java:89)
 at org.apache.iceberg.CachingCatalog.registerTable(CachingCatalog.java:193)
 at org.apache.iceberg.spark.procedures.RegisterTableProcedure.call(RegisterTableProcedure.java:89)
 at org.apache.spark.sql.execution.datasources.v2.CallExec.run(CallExec.scala:34)
 at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
 at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
 at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
 at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
 at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
 at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
 at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
 at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
 at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
 at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
 at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
 at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
 at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
 at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
 at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
 at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
 at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
 at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
 at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
 at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
 at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
 at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
 at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
 at org.apache.spark.sql.Dataset.<init>(Dataset.scala:220)
 at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
 at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
 at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
 at org.apache.spark.sql.SparkSession.$anonfun$sql$4(SparkSession.scala:691)
 at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
 at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:682)
 at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:713)
 at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:744)
 at com.striim.NessieToS3CatalogMigrator.main(NessieToS3CatalogMigrator.java:24)
Caused by: software.amazon.awssdk.services.s3tables.model.NotFoundException: The specified table does not exist. (Service: S3Tables, Status Code: 404, Request ID: 906eccc1-1aec-4179-b2bb-b115dda89f7b)
 at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
 at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
 at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
 at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:50)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:38)
 at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:74)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:43)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:79)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:41)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:55)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:39)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage2.executeRequest(RetryableStage2.java:93)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage2.execute(RetryableStage2.java:56)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage2.execute(RetryableStage2.java:36)
 at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
 at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:53)
 at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:35)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:82)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:62)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:43)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:32)
 at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
 at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
 at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
 at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:210)
 at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
 at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:173)
 at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:80)
 at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182)
 at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74)
 at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
 at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)
 at software.amazon.awssdk.services.s3tables.DefaultS3TablesClient.getTableMetadataLocation(DefaultS3TablesClient.java:1168)
 at software.amazon.s3tables.iceberg.S3TablesCatalogOperations.doCommit(S3TablesCatalogOperations.java:197)
 ... 38 more

```

Also , if this is a bug , I'm happy to contribute with some guidance from the team.

**Comment by stubz151** [comment]
I think it has to do with the doCommit not creating a table if it can't find one:
instead we are doing table creation [here](https://github.com/awslabs/s3-tables-catalog/blob/main/src/software/amazon/s3tables/iceberg/S3TablesCatalog.java#L202): [](url)

I think adding table creation to the do commit would help here. We didn't think of this use case.

**Comment by Karthilearns** [comment]
Got it , Can any of the committers help on proceeding with this issue. Happy to contribute

**Comment by stubz151** [comment]
I'm happy to review the pr. Otherwise I can take a look when I get a chance. But I would just check the flow for this stored procedure because it's different to the normal create table flow. And then add the create table call where we can.

**Comment by stubz151** [comment]
https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java#L91 Looks like the base has an implementation that uses commit with an empty table base. Am testing a fix where we create a new table based off of this.

**Comment by stubz151** [comment]
https://github.com/awslabs/s3-tables-catalog/tree/register_table can test this out. Am getting a weird 400 that I'm investigating.

**Comment by stubz151** [comment]
Could you clone that branch and build and test with it?
I had to do some interesting stuff for this to work but it seems to be working for my commands at least.

**Comment by stubz151** [comment]
cut a pr: https://github.com/awslabs/s3-tables-catalog/pull/25
Please test and let me know
