### ISSUE TITLE
NoClassDefFoundError: software/amazon/awssdk/services/s3/model/S3Exception

### ISSUE THREAD

**Issue by bhaskar-pv** [awslabs/s3-tables-catalog#27]
I am connecting to spark-shell via following:

```
spark-shell \
--packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.4.0,software.amazon.s3tables:s3-tables-catalog-for-iceberg-runtime:0.1.3 \
--conf spark.sql.catalog.s3tablesbucket=org.apache.iceberg.spark.SparkCatalog \
--conf spark.sql.catalog.s3tablesbucket.catalog-impl=software.amazon.s3tables.iceberg.S3TablesCatalog \
--conf spark.sql.catalog.s3tablesbucket.warehouse={arn detail} \
--conf spark.sql.defaultCatalog=s3tablesbucket \
--conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
```

Once I am connected, If I do `spark.sql("show tables").show()`

I am getting the tables:

scala> spark.sql("show tables").show()
+-----------+---------------+---------------+
|namespace |    tableName.    |  isTemporary.   |
+-----------+---------------+---------------+
|tbl_space    |example_table. |      false             |
+-----------+---------------+---------------+

But when I am running `spark.sql("select * from s3tablesbucket.tbl_space.example_table").show()` I am getting following error

```
java.lang.NoClassDefFoundError: software/amazon/awssdk/services/s3/model/S3Exception
  at software.amazon.s3tables.iceberg.S3TablesCatalogOperations.initializeFileIO(S3TablesCatalogOperations.java:111)
  at software.amazon.s3tables.iceberg.S3TablesCatalogOperations.io(S3TablesCatalogOperations.java:99)
  at software.amazon.s3tables.iceberg.imports.FileIOTracker.track(FileIOTracker.java:53)
  at software.amazon.s3tables.iceberg.S3TablesCatalog.newTableOps(S3TablesCatalog.java:178)
  at software.amazon.s3tables.iceberg.S3TablesCatalog.loadTable(S3TablesCatalog.java:114)
  at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406)
  at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
  at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404)
  at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387)
  at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
  at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
  at org.apache.iceberg.CachingCatalog.loadTable(CachingCatalog.java:166)
  at org.apache.iceberg.spark.SparkCatalog.load(SparkCatalog.java:643)
  at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:159)
  at org.apache.spark.sql.connector.catalog.CatalogV2Util$.getTable(CatalogV2Util.scala:363)
```

**Comment by stubz151** [comment]
If you add the AWS-bundle to your packages it should work.
