### ISSUE TITLE
Cannot run spark-shell using OSS spark

### ISSUE THREAD

**Issue by tundraraj** [awslabs/s3-tables-catalog#29]
Hi,
Per https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-tables-integrating-open-source-spark.html, tried to start a spark-shell  session but it errored out.

Spark version - 3.5.3
Python - 3.9.13

Admin:~/environment $ spark-shell \
> --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.6.1,software.amazon.s3tables:s3-tables-catalog-for-iceberg-runtime:0.1.3 \
> --conf spark.sql.catalog.s3tablesbucket=org.apache.iceberg.spark.SparkCatalog \
> --conf spark.sql.catalog.s3tablesbucket.catalog-impl=software.amazon.s3tables.iceberg.S3TablesCatalog \
> --conf spark.sql.catalog.s3tablesbucket.warehouse=arn:aws:s3tables:us-east-1:xxxxxxxxxxxxx:bucket/test-table-bucket-1 \
> --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
:: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /home/ec2-user/.ivy2/cache
The jars for the packages stored in: /home/ec2-user/.ivy2/jars
org.apache.iceberg#iceberg-spark-runtime-3.5_2.12 added as a dependency
software.amazon.s3tables#s3-tables-catalog-for-iceberg-runtime added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-4e330064-e52e-4e3e-aff4-95f7950f33c5;1.0
        confs: [default]
        found org.apache.iceberg#iceberg-spark-runtime-3.5_2.12;1.6.1 in central
        found software.amazon.s3tables#s3-tables-catalog-for-iceberg-runtime;0.1.3 in central
:: resolution report :: resolve 253ms :: artifacts dl 11ms
        :: modules in use:
        org.apache.iceberg#iceberg-spark-runtime-3.5_2.12;1.6.1 from central in [default]
        software.amazon.s3tables#s3-tables-catalog-for-iceberg-runtime;0.1.3 from central in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
        ---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-4e330064-e52e-4e3e-aff4-95f7950f33c5
        confs: [default]
        0 artifacts copied, 2 already retrieved (0kB/9ms)
24/12/25 15:54:05 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.5.3
      /_/
         
Using Scala version 2.13.8 (OpenJDK 64-Bit Server VM, Java 21.0.5)
Type in expressions to have them evaluated.
Type :help for more information.
ReplGlobal.abort: bad constant pool index: 0 at pos: 48454
ReplGlobal.abort: bad constant pool index: 0 at pos: 48454
Exception in thread "main" scala.reflect.internal.FatalError: 
  bad constant pool index: 0 at pos: 48454
     while compiling: <no file>
        during phase: globalPhase=<no phase>, enteringPhase=<some phase>
     library version: version 2.13.8
    compiler version: version 2.13.8
  reconstructed args: -classpath /home/ec2-user/.ivy2/jars/org.apache.iceberg_iceberg-spark-runtime-3.5_2.12-1.6.1.jar:/home/ec2-user/.ivy2/jars/software.amazon.s3tables_s3-tables-catalog-for-iceberg-runtime-0.1.3.jar -Yrepl-class-based -Yrepl-outdir /tmp/spark-e677e5cf-5253-4341-9648-26d16fac65ff/repl-b1f032d9-11aa-4d04-a951-051a1a04ae96

  last tree to typer: EmptyTree
       tree position: <unknown>
            tree tpe: <notype>
              symbol: null
           call site: <none> in <none>

== Source file context for tree position ==

        at scala.reflect.internal.Reporting.abort(Reporting.scala:69)
        at scala.reflect.internal.Reporting.abort$(Reporting.scala:65)
        at scala.tools.nsc.interpreter.IMain$$anon$1.scala$tools$nsc$interpreter$ReplGlobal$$super$abort(IMain.scala:149)
        at scala.tools.nsc.interpreter.ReplGlobal.abort(ReplGlobal.scala:27)
        at scala.tools.nsc.interpreter.ReplGlobal.abort$(ReplGlobal.scala:24)
        at scala.tools.nsc.interpreter.IMain$$anon$1.abort(IMain.scala:149)
        at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.errorBadIndex(ClassfileParser.scala:407)
        at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.getExternalName(ClassfileParser.scala:262)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.readParamNames$1(ClassfileParser.scala:853)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttribute$1(ClassfileParser.scala:859)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parseAttributes$6(ClassfileParser.scala:936)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttributes(ClassfileParser.scala:936)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.parseMethod(ClassfileParser.scala:635)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:548)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$2(ClassfileParser.scala:174)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$1(ClassfileParser.scala:159)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:142)
        at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:342)
        at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.$anonfun$complete$2(SymbolLoaders.scala:249)
        at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:247)
        at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1561)
        at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1533)
        at scala.reflect.internal.Definitions.scala$reflect$internal$Definitions$$enterNewMethod(Definitions.scala:47)
        at scala.reflect.internal.Definitions$DefinitionsClass.String_$plus$lzycompute(Definitions.scala:1256)
        at scala.reflect.internal.Definitions$DefinitionsClass.String_$plus(Definitions.scala:1256)
        at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreMethods$lzycompute(Definitions.scala:1577)
        at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreMethods(Definitions.scala:1559)
        at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1590)
        at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1590)
        at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1646)
        at scala.tools.nsc.Global$Run.<init>(Global.scala:1226)
        at scala.tools.nsc.interpreter.IMain.liftedTree1$1(IMain.scala:152)
        at scala.tools.nsc.interpreter.IMain.global$lzycompute(IMain.scala:151)
        at scala.tools.nsc.interpreter.IMain.global(IMain.scala:142)
        at scala.tools.nsc.interpreter.IMain.withSuppressedSettings(IMain.scala:106)
        at scala.tools.nsc.interpreter.shell.ILoop.$anonfun$run$1(ILoop.scala:954)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.tools.nsc.interpreter.shell.ReplReporterImpl.withoutPrintingResults(Reporter.scala:64)
        at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:954)
        at org.apache.spark.repl.Main$.doMain(Main.scala:84)
        at org.apache.spark.repl.Main$.main(Main.scala:59)
        at org.apache.spark.repl.Main.main(Main.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:75)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by jamesbornholt** [comment]
This looks like a mismatch of Scala versions. Could you try changing “2.12” to “2.13” in the middle of the `--packages` argument you pass to spark-shell?

**Comment by tundraraj** [comment]
Getting the same issue

spark-shell --packages org.apache.iceberg:iceberg-spark-runtime-3.5_**2.13**:1.6.1,software.amazon.s3tables:s3-tables-catalog-for-iceberg-runtime:0.1.3 --conf spark.sql.catalog.s3tablesbucket=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.s3tablesbucket.catalog-impl=software.amazon.s3tables.iceberg.S3TablesCatalog --conf spark.sql.catalog.s3tablesbucket.warehouse=arn:aws:s3tables:us-east-1:062690204536:bucket/test-table-bucket-1 --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions --verbose

**Comment by mattgillard** [comment]
I am successfully using the spark:3.5.3 official docker container which has Scala 2.12. Documented in this blog post: https://medium.com/@mattgillard/my-s3-tables-experiment-a789493c5512
